export const ENDPOINTS = {
  session: '/api/auth/session',
  platformConfig: '/api/auth/session',
  login: '/login',
  establish: '/api/auth/session',
  logout: '/api/auth/logout',
  load: '/api/bio/load',
  save: '/api/bio/save',
  publish: '/api/bio/publish',
  revert: '/api/bio/revert',
  restoreBackup: '/api/bio/restore-backup',
  paths: '/api/bio/paths',
  upload: '/api/assets/upload',
  listAssets: '/api/assets/list',
  deleteAsset: '/api/assets/delete',
  updateStatus: '/api/update/status',
  updateCheck: '/api/update/check',
  updateApply: '/api/update/apply',
  analyticsSummary: '/api/analytics/summary',
  analyticsTimeseries: '/api/analytics/timeseries',
  analyticsClicks: '/api/analytics/clicks',
  resolveMaps: '/api/maps/resolve',
  bioPages: '/api/bio/pages',
} as const
